### ISSUE TITLE
1.12.2 support

### ISSUE THREAD

**Issue by Agrrox** [andrewlalis/RailSignalAPI#1]
Hello, does RailSignalAPI work on 1.12.2?

**Comment by PiglinPlayz** [comment]
As far as i know there is only 1.16.5 support but im dm the dev to see if he has a plan for 1.12.2 support because i have some mods that are on 1.12 that would look amazing with this api


> Hello, does RailSignalAPI work on 1.12.2?

**Comment by PiglinPlayz** [comment]
this supports any version according to the dev,
